### ISSUE TITLE
ArchLinux 启动报错

### ISSUE THREAD

**Issue by cellargalaxy** [top-bettercode/docker-wechat#62]
启动容器后界面不出来，进入容器执行run.sh脚本报错

docker命令

```shell
docker run -d \
--name wechat \
--device /dev/snd \
--ipc="host" \
-v /tmp/.X11-unix:/tmp/.X11-unix \
-v $HOME/software/WeChatFiles:/WeChatFiles \
-e DISPLAY=$DISPLAY \
-e XMODIFIERS=@im=fcitx \
-e QT_IM_MODULE=fcitx \
-e GTK_IM_MODULE=fcitx \
-e AUDIO_GID=`getent group audio | cut -d: -f3` \
-e GID=`id -g` \
-e UID=`id -u` \
bestwu/wechat
```

```shell
$ docker exec -it wechat bash

root@7950b978326d:/# /opt/apps/com.qq.weixin.deepin/files/run.sh
bash: /opt/apps/com.qq.weixin.deepin/files/run.sh: 没有那个文件或目录
root@7950b978326d:/# /opt/deepinwine/apps/Deepin-WeChat/run.sh
Run Deepin-WeChat 2.6.8.65deepin0 c:/Program Files/Tencent/WeChat/WeChat.exe
run Deepin-WeChat progress pid 
Authorization required, but no authorization protocol specified
Unable to init server: Could not connect: 拒绝连接

(zenity:320): Gtk-WARNING **: cannot open display: :0
Authorization required, but no authorization protocol specified
Unable to init server: Could not connect: 拒绝连接

(zenity:324): Gtk-WARNING **: cannot open display: :0
mv: '/root/.deepinwine/Deepin-WeChat/drive_c/users/@current_user@' and '/root/.deepinwine/Deepin-WeChat/drive_c/users/@current_user@' are the same file
total 88
lrwxrwxrwx 1 root root 10 1月  20 13:49 c: -> ../drive_c
lrwxrwxrwx 1 root root 10 1月  20 13:49 com1 -> /dev/ttyS0
lrwxrwxrwx 1 root root 10 1月  20 13:49 com10 -> /dev/ttyS9
lrwxrwxrwx 1 root root 11 1月  20 13:49 com11 -> /dev/ttyS10
lrwxrwxrwx 1 root root 11 1月  20 13:49 com12 -> /dev/ttyS11
lrwxrwxrwx 1 root root 11 1月  20 13:49 com13 -> /dev/ttyS12
lrwxrwxrwx 1 root root 11 1月  20 13:49 com14 -> /dev/ttyS13
lrwxrwxrwx 1 root root 11 1月  20 13:49 com15 -> /dev/ttyS14
lrwxrwxrwx 1 root root 11 1月  20 13:49 com16 -> /dev/ttyS15
lrwxrwxrwx 1 root root 10 1月  20 13:49 com2 -> /dev/ttyS1
lrwxrwxrwx 1 root root 10 1月  20 13:49 com3 -> /dev/ttyS2
lrwxrwxrwx 1 root root 10 1月  20 13:49 com4 -> /dev/ttyS3
lrwxrwxrwx 1 root root 10 1月  20 13:49 com5 -> /dev/ttyS4
lrwxrwxrwx 1 root root 10 1月  20 13:49 com6 -> /dev/ttyS5
lrwxrwxrwx 1 root root 10 1月  20 13:49 com7 -> /dev/ttyS6
lrwxrwxrwx 1 root root 10 1月  20 13:49 com8 -> /dev/ttyS7
lrwxrwxrwx 1 root root 10 1月  20 13:49 com9 -> /dev/ttyS8
lrwxrwxrwx 1 root root  8 1月  20 13:49 d:: -> /dev/sdb
lrwxrwxrwx 1 root root 17 1月  20 13:49 e: -> /media/wayne/Ntfs
lrwxrwxrwx 1 root root  9 1月  20 13:49 e:: -> /dev/sdb1
lrwxrwxrwx 1 root root  5 1月  20 13:49 y: -> /root
lrwxrwxrwx 1 root root  1 1月  20 13:49 z: -> /
CallApp Deepin-WeChat c:/Program Files/Tencent/WeChat/WeChat.exe
Disable auto update
rm: cannot remove '/root/.deepinwine/Deepin-WeChat/drive_c/users//Application Data/Tencent/WeChat/All Users/config/configEx.ini': 没有那个文件或目录
2024年 01月 20日 星期六 13:50:19 UTC:kill WeChat.exe block
2024年 01月 20日 星期六 13:50:19 UTC:tag bottle: 
process 517: D-Bus library appears to be incorrectly set up; failed to read machine uuid: Failed to open "/etc/machine-id": No such file or directory
See the manual page for dbus-uuidgen to correct this issue.
Traceback (most recent call last):
  File "/opt/deepinwine/tools/get_tray_window", line 28, in <module>
    get_tray_window()
  File "/opt/deepinwine/tools/get_tray_window", line 17, in get_tray_window
    bus = dbus.SessionBus()
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
Authorization required, but no authorization protocol specified
xprop:  unable to open display ':0'
2024年 01月 20日 星期六 13:50:19 UTC:active bottles: 
/root/.deepinwine/Deepin-WeChat/drive_c/Program Files/Tencent/WeChat
Starting process c:/Program Files/Tencent/WeChat/WeChat.exe ...
root@7950b978326d:/# Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified

[0120/135019:FATAL:temp_window.cc(43)] Check failed: hwnd_. 
Backtrace:
	(No symbol) [0x02CA0AB1]
	(No symbol) [0x02B7EB7F]
	(No symbol) [0x02B64861]
	(No symbol) [0x02561982]
	(No symbol) [0x106AA955]
	(No symbol) [0x101F27FB]
	(No symbol) [0x101F053B]
	(No symbol) [0x106DDED0]
	(No symbol) [0x106DDE09]
	(No symbol) [0x106D9F29]
	(No symbol) [0x106DA4DA]
	(No symbol) [0x1022BD58]
	(No symbol) [0x101F2D12]
	(No symbol) [0x106DF9BE]
	WINPROC_wrapper [0x7E90849A+26]
	(No symbol) [0x7E908B0A]
	(No symbol) [0x7E90ADA5]
	(No symbol) [0x7E8CD4C2]
	(No symbol) [0x7E8D3E3C]
	SendMessageW [0x7E8D4094+84]
	(No symbol) [0x7E8FECF1]
	CreateWindowExW [0x7E8F8138+120]
	(No symbol) [0x106DF5AC]
	(No symbol) [0x106DA270]
	(No symbol) [0x106B638C]
	(No symbol) [0x106B6F99]
	(No symbol) [0x00401918]
	(No symbol) [0x004030B9]
	call_process_entry [0x7B85F80C+12]
	ExitProcess [0x7B860789+3961]
	call_thread_func_wrapper [0x7BC7EEDC+12]
	(No symbol) [0x7BC82089]
	RtlRaiseException [0x7BC7EEBA+74]
	(No symbol) [0x00000000]

Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
```

**Comment by cellargalaxy** [comment]
需要执行`xhost +`
